### PR TITLE
Merge api stack

### PR DESCRIPTION
**Pull request by Mrymk02**

### CODE REVIEW

**Comment by Mrymk02** [comment]
Removed StandardAPI and EmailAPI Stacks because all routes are in APIStack. 
Review and approve please :)

**Review by FatimaJ20 — DISMISSED** [review]
All good

**Comment by Mrymk02** [comment]
# Resolving Conflicts with main

Checkout via command line
If the conflicts on this branch are too complex to resolve in the web editor, you can check it out via command line to resolve the conflicts.

Step 1: Clone the repository or update your local repository with the latest changes.

`git pull origin main
`

Step 2: Switch to the head branch of the pull request.

`git checkout Merge-APIStack
`

Step 3: Merge the base branch into the head branch.

`git merge main
`

Step 4: Fix the conflicts and commit the result.

See [Resolving a merge conflict using the command line](https://docs.github.com/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) for step-by-step instructions on resolving merge conflicts.

Step 5: Push the changes.

`git push -u origin Merge-APIStack`

**Review by FatimaJ20 — DISMISSED** [review]
All good

**Review by FatimaJ20 — APPROVED** [review]
All good!

**Pull request merged**
